# Generated by Django 5.0.3 on 2024-03-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Condo', 'Condo'), ('TownHouse', 'TownHouse'), ('Apartment', 'Apartment'), ('House', 'House'), ('Modular Home', 'Modular Home'), ('Single-Family House', 'Single-Family House')], max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('bedRooms', models.PositiveIntegerField()),
                ('bathRooms', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('is_for_rent', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
        ),
    ]
